<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>resetpwd</title>
		<link rel="stylesheet" href="/resetpwd/public/css/reglog.css" type="text/css">
	</head>

	<body>
		<div class="seagate-header-bar">
			<img class="img-logo" src='/resetpwd/public/image/seagate-logo.png' alt="seagate">
		</div>
		<div class="error-msg-bar">
			<img  src='/resetpwd/public/image/error.png' alt="success"><span id="error-msg">Your pass word should be at least six characters,please try again.</span>
		</div>
		<!--START reset pwd-->
		<div class="seagate-main-content">			
			<h2><?php echo $t["Header"] ?></h2>
			<label>Enter your email address to reset your password</label>
			<p class="tip">You may need to check your spam folder or unblock no-reply@seagate.com</p>
			<?php echo Phalcon\Tag::form('index/commit') ?>
				<p>
					<?php echo Phalcon\Tag::textField("email") ?>
				</p>

				<p>
					<?php echo Phalcon\Tag::submitButton("Commit") ?>
				</p>

			</form>
		</div>
		<!--END reset pwd-->
		<div class="footer">
			<div class="footer-content">
				<div class="language">Language：
					<span class="selecte"><span id="selected">English</span><span class="down">▼</span><span class="up">▲</span>
						<ul>
							<li><?php echo Phalcon\Tag::linkTo("set-language/en", "English") ?></li><li>Français</li><li>Italiano</li><li>Deutsch</li><li>Español</li><li>Nederlands</li><li>Português</li><li>русский</li><li>简体中文</li><li>繁體中文</li><li>한국어</li><li><?php echo Phalcon\Tag::linkTo("set-language/ja", "日本语") ?></li>
						</ul>
					</span>
					
				</div>
				<span class="copy">©2012 Seagate Technology LLC</span>
			</div>
		</div>
	</body>
</html>
