<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>resetpwd</title>
		<link rel="stylesheet" href="/resetpwd/public/css/reglog.css" type="text/css">
	</head>

	<body>
		<div class="seagate-header-bar">
			<img class="img-logo" src='/resetpwd/public/image/seagate-logo.png' alt="seagate">
		</div>
		<!--START email has been sent-->
		<div class="seagate-main-content mail-has-been-sent">
			<h2>Reset your Seagate Password</h2>
			<p>An e-mail has been sent to mathai.varghese@gmail.com with further instructions.</p>
		</div>
		<!--END email has been sent-->
		<div class="footer">
			<div class="footer-content">
				<div class="language">Language：
					<span class="selecte"><span id="selected">English</span><span class="down">▼</span><span class="up">▲</span>
						<ul>
							<li>English</li><li>Français</li><li>Italiano</li><li>Deutsch</li><li>Español</li><li>Nederlands</li><li>Português</li><li>русский</li><li>简体中文</li><li>繁體中文</li><li>한국어</li><li>日本語</li>
						</ul>
					</span>
					
				</div>
				<span class="copy">©2012 Seagate Technology LLC</span>
			</div>
		</div>
	</body>
</html>
