<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>resetpwd</title>
		<link rel="stylesheet" href="/resetpwd/public/css/reglog.css" type="text/css">
	</head>

	<body>
		<div class="seagate-header-bar">
			<img class="img-logo" src='/resetpwd/public/image/seagate-logo.png' alt="seagate">
		</div>
		<div class="error-msg-bar">
			<img  src='<?php echo $imageError ?>' alt="success"><span id="error-msg">Your pass word should be at least six characters,please try again.</span>
		</div>
		<!--START reset pwd-->
		<div class="seagate-main-content">
			<h2>Reset your Seagate Password</h2>
			<?php echo Phalcon\Tag::form('index/resetpwd') ?>
				<p>
					<label for="name">E-Mail</label>
					<?php echo Phalcon\Tag::textField(array("email","value"=>$email)) ?>
				</p>
				<p>
					<label>Enter new password</label>
					<?php echo Phalcon\Tag::passwordField("pwd") ?>
				</p>
				<p>
					<label>Confirm new password</label>
					<?php echo Phalcon\Tag::passwordField("pwd2") ?>
					<?php echo Phalcon\Tag::hiddenField  (array("token","value"=>$token)) ?>
				</p>
				<p>

					<?php echo Phalcon\Tag::submitButton("Commit") ?>
				</p>

			</form>
		</div>
		<!--END reset pwd-->

		<div class="footer">
			<div class="footer-content">
				<div class="language">Language：
					<span class="selecte"><span id="selected">English</span><span class="down">▼</span><span class="up">▲</span>
						<ul>
							<li>English</li><li>Français</li><li>Italiano</li><li>Deutsch</li><li>Español</li><li>Nederlands</li><li>Português</li><li>русский</li><li>简体中文</li><li>繁體中文</li><li>한국어</li><li>日本語</li>
						</ul>
					</span>
					
				</div>
				<span class="copy">©2012 Seagate Technology LLC</span>
			</div>
		</div>
	</body>
</html>
